'''
Created on Jan 21, 2016

@author: Ivan Ivanov
'''

import networkx as nx

##################################################
# For test_graph
##################################################

##################################################
# For test_arnborg_prokurowski
##################################################

##################################################
# For test_similar_nodes_mining
##################################################
snm_dummy_graph = nx.MultiDiGraph()
snm_dummy_graph.add_node(1, labels=["r"])
snm_dummy_graph.add_node(2, labels=["r"])
snm_dummy_graph.add_node(3, labels=["r"])
snm_dummy_graph.add_node(4, labels=["b"])
snm_dummy_graph.add_node(5, labels=["r"])
snm_dummy_graph.add_node(6, labels=["b"])
snm_dummy_graph.add_node(7, labels=["b"])
snm_dummy_graph.add_node(8, labels=["b", "r"])
snm_dummy_graph.add_node(9, labels=["r"])
snm_dummy_graph.add_node(10, labels=["b"])
snm_dummy_graph.add_node(11, labels=["b", "r"])
snm_dummy_graph.add_node(12, labels=["b", "r"])
snm_dummy_graph.add_edge(1, 8, label="g")
snm_dummy_graph.add_edge(2, 1, label="n")
snm_dummy_graph.add_edge(2, 3, label="g")
snm_dummy_graph.add_edge(3, 5, label="n")
snm_dummy_graph.add_edge(3, 6, label="n")
snm_dummy_graph.add_edge(4, 3, label="g")
snm_dummy_graph.add_edge(6, 2, label="n")
snm_dummy_graph.add_edge(7, 2, label="n")
snm_dummy_graph.add_edge(8, 7, label="n")
snm_dummy_graph.add_edge(8, 9, label="n")
snm_dummy_graph.add_edge(10, 8, label="g")
snm_dummy_graph.add_edge(11, 1, label="n")
snm_dummy_graph.add_edge(11, 12, label="n")

snm_dummy_graph_features = []

snm_dummy_graph_features.append(nx.MultiDiGraph())
snm_dummy_graph_features[-1].add_node("n_2", labels=["r"])
snm_dummy_graph_features[-1].add_node("n_1", labels=["r"])
snm_dummy_graph_features[-1].add_edge("n_2", "n_1", label="n")

snm_dummy_graph_features.append(nx.MultiDiGraph())
snm_dummy_graph_features[-1].add_node("n_2", labels=["r"])
snm_dummy_graph_features[-1].add_node("n_3", labels=["r"])
snm_dummy_graph_features[-1].add_edge("n_2", "n_3", label="g")

snm_dummy_graph_features.append(nx.MultiDiGraph())
snm_dummy_graph_features[-1].add_node("n_2", labels=["wl_7"])
snm_dummy_graph_features[-1].add_node("n_1", labels=["wl_6"])
snm_dummy_graph_features[-1].add_edge("n_2", "n_1", label="wl_4")

snm_dummy_graph_features.append(nx.MultiDiGraph())
snm_dummy_graph_features[-1].add_node("n_2", labels=["wl_7"])
snm_dummy_graph_features[-1].add_node("n_3", labels=["wl_5"])
snm_dummy_graph_features[-1].add_edge("n_2", "n_3", label="wl_3")

snm_dummy_graph_features.append(nx.MultiDiGraph())
snm_dummy_graph_features[-1].add_node("n_2", labels=["r"])
snm_dummy_graph_features[-1].add_node("n_6", labels=["b"])
snm_dummy_graph_features[-1].add_edge("n_6", "n_2", label="n")

snm_dummy_graph_features.append(nx.MultiDiGraph())
snm_dummy_graph_features[-1].add_node("n_2", labels=["r"])
snm_dummy_graph_features[-1].add_node("n_7", labels=["b"])
snm_dummy_graph_features[-1].add_edge("n_7", "n_2", label="n")
# /-------------------------------------------------------

# --------------------------------------------------------
snm_dummy_feature = nx.MultiDiGraph()
snm_dummy_feature.add_node("n_1", labels=["1", "2"])
snm_dummy_feature.add_node("n_2", labels=["3"])
snm_dummy_feature.add_node("n_3", labels=["4", "5", "6"])
snm_dummy_feature.add_edge("n_1", "n_2", label="7")
snm_dummy_feature.add_edge("n_3", "n_1", label="7")
# /-------------------------------------------------------

# --------------------------------------------------------
# graph containing all three types of features (fixed, pattern and dynamic)
snm_dummy_graph_2 = nx.MultiDiGraph()
# ring (2.2.0.0)
snm_dummy_graph_2.add_node(1, labels=["b", "r"])
snm_dummy_graph_2.add_node(2, labels=["b"])
snm_dummy_graph_2.add_node(3, labels=["b", "r"])
snm_dummy_graph_2.add_node(4, labels=["r"])
snm_dummy_graph_2.add_node(5, labels=["b"])
snm_dummy_graph_2.add_node(6, labels=["b", "r"])
snm_dummy_graph_2.add_node(7, labels=["r"])
snm_dummy_graph_2.add_node(8, labels=["b"])
snm_dummy_graph_2.add_node(9, labels=["b"])
snm_dummy_graph_2.add_edge(2, 1, label="n")
snm_dummy_graph_2.add_edge(3, 2, label="g")
snm_dummy_graph_2.add_edge(3, 4, label="n")
snm_dummy_graph_2.add_edge(4, 5, label="n")
snm_dummy_graph_2.add_edge(6, 5, label="g")
snm_dummy_graph_2.add_edge(6, 7, label="n")
snm_dummy_graph_2.add_edge(7, 8, label="n")
snm_dummy_graph_2.add_edge(9, 8, label="g")
snm_dummy_graph_2.add_edge(9, 1, label="n")
# auxiliary structure: cat's cradle (6.1.0.0)
snm_dummy_graph_2.add_node(21, labels=["G"])
snm_dummy_graph_2.add_node(22, labels=["G"])
snm_dummy_graph_2.add_node(23, labels=["G"])
snm_dummy_graph_2.add_node(24, labels=["G"])
snm_dummy_graph_2.add_node(25, labels=["G"])
snm_dummy_graph_2.add_node(26, labels=["G"])
snm_dummy_graph_2.add_edge(21, 22, label="n")
snm_dummy_graph_2.add_edge(21, 24, label="n")
snm_dummy_graph_2.add_edge(21, 26, label="n")
snm_dummy_graph_2.add_edge(22, 23, label="n")
snm_dummy_graph_2.add_edge(22, 25, label="n")
snm_dummy_graph_2.add_edge(23, 24, label="n")
snm_dummy_graph_2.add_edge(23, 26, label="n")
snm_dummy_graph_2.add_edge(24, 25, label="n")
snm_dummy_graph_2.add_edge(25, 26, label="n")
# chain (2.1.0.0)
snm_dummy_graph_2.add_node(11, labels=["b", "r"])
snm_dummy_graph_2.add_node(12, labels=["b"])
snm_dummy_graph_2.add_node(13, labels=["b", "r"])
snm_dummy_graph_2.add_node(14, labels=["r"])
snm_dummy_graph_2.add_node(15, labels=["b"])
snm_dummy_graph_2.add_node(16, labels=["b", "r"])
snm_dummy_graph_2.add_node(17, labels=["r"])
snm_dummy_graph_2.add_node(18, labels=["b"])
snm_dummy_graph_2.add_node(19, labels=["b"])
snm_dummy_graph_2.add_edge(11, 26, label="n")
snm_dummy_graph_2.add_edge(12, 11, label="n")
snm_dummy_graph_2.add_edge(13, 12, label="g")
snm_dummy_graph_2.add_edge(13, 14, label="n")
snm_dummy_graph_2.add_edge(14, 15, label="n")
snm_dummy_graph_2.add_edge(16, 15, label="g")
snm_dummy_graph_2.add_edge(16, 17, label="n")
snm_dummy_graph_2.add_edge(17, 18, label="n")
snm_dummy_graph_2.add_edge(19, 18, label="g")
snm_dummy_graph_2.add_edge(19, 11, label="n")
# cube (4.3.0.0)
snm_dummy_graph_2.add_node(50, labels=["G"]) # hub
snm_dummy_graph_2.add_node(51, labels=["0"])
snm_dummy_graph_2.add_node(52, labels=["0"])
snm_dummy_graph_2.add_node(53, labels=["0"])
snm_dummy_graph_2.add_edge(50, 51, label="n")
snm_dummy_graph_2.add_edge(50, 52, label="n")
snm_dummy_graph_2.add_edge(50, 53, label="n")
snm_dummy_graph_2.add_edge(51, 21, label="n")
snm_dummy_graph_2.add_edge(51, 25, label="n")
snm_dummy_graph_2.add_edge(52, 21, label="n")
snm_dummy_graph_2.add_edge(52, 23, label="n")
snm_dummy_graph_2.add_edge(53, 23, label="n")
snm_dummy_graph_2.add_edge(53, 25, label="n")
# buddy (4.2.0.0)
snm_dummy_graph_2.add_node(60, labels=["0"])
snm_dummy_graph_2.add_node(61, labels=["0"])
snm_dummy_graph_2.add_node(62, labels=["0"])
snm_dummy_graph_2.add_node(70, labels=["0"])
snm_dummy_graph_2.add_node(71, labels=["0"])
snm_dummy_graph_2.add_node(72, labels=["0"])
snm_dummy_graph_2.add_node(80, labels=["0"])
snm_dummy_graph_2.add_node(81, labels=["0"])
snm_dummy_graph_2.add_node(82, labels=["0"])
snm_dummy_graph_2.add_edge(70, 60, label="n")
snm_dummy_graph_2.add_edge(70, 61, label="n")
snm_dummy_graph_2.add_edge(70, 62, label="n")
snm_dummy_graph_2.add_edge(71, 60, label="n")
snm_dummy_graph_2.add_edge(71, 61, label="n")
snm_dummy_graph_2.add_edge(71, 62, label="n")
snm_dummy_graph_2.add_edge(72, 60, label="n")
snm_dummy_graph_2.add_edge(72, 61, label="n")
snm_dummy_graph_2.add_edge(72, 62, label="n")
snm_dummy_graph_2.add_edge(80, 60, label="n")
snm_dummy_graph_2.add_edge(80, 61, label="n")
snm_dummy_graph_2.add_edge(80, 62, label="n")
snm_dummy_graph_2.add_edge(81, 60, label="n")
snm_dummy_graph_2.add_edge(81, 61, label="n")
snm_dummy_graph_2.add_edge(81, 62, label="n")
snm_dummy_graph_2.add_edge(82, 60, label="n")
snm_dummy_graph_2.add_edge(82, 61, label="n")
snm_dummy_graph_2.add_edge(82, 62, label="n")
# wheel (5.2.3.1)
snm_dummy_graph_2.add_node(90, labels=["G"])
snm_dummy_graph_2.add_node(91, labels=["b", "r"])
snm_dummy_graph_2.add_node(92, labels=["b"])
snm_dummy_graph_2.add_node(93, labels=["b", "r"])
snm_dummy_graph_2.add_node(94, labels=["r"])
snm_dummy_graph_2.add_node(95, labels=["b"])
snm_dummy_graph_2.add_node(96, labels=["b", "r"])
snm_dummy_graph_2.add_node(97, labels=["r"])
snm_dummy_graph_2.add_node(98, labels=["b"])
snm_dummy_graph_2.add_node(99, labels=["b"])
snm_dummy_graph_2.add_edge(90, 91, label="n")
snm_dummy_graph_2.add_edge(90, 92, label="n")
snm_dummy_graph_2.add_edge(90, 93, label="n")
snm_dummy_graph_2.add_edge(90, 94, label="n")
snm_dummy_graph_2.add_edge(90, 95, label="n")
snm_dummy_graph_2.add_edge(90, 96, label="n")
snm_dummy_graph_2.add_edge(90, 97, label="n")
snm_dummy_graph_2.add_edge(90, 98, label="n")
snm_dummy_graph_2.add_edge(90, 99, label="n")
snm_dummy_graph_2.add_edge(92, 91, label="n")
snm_dummy_graph_2.add_edge(93, 92, label="g")
snm_dummy_graph_2.add_edge(93, 94, label="n")
snm_dummy_graph_2.add_edge(94, 95, label="n")
snm_dummy_graph_2.add_edge(96, 95, label="g")
snm_dummy_graph_2.add_edge(96, 97, label="n")
snm_dummy_graph_2.add_edge(97, 98, label="n")
snm_dummy_graph_2.add_edge(99, 98, label="g")
snm_dummy_graph_2.add_edge(99, 91, label="n")
# rule 5.2.2
snm_dummy_graph_2.add_node(100, labels=["0"])
snm_dummy_graph_2.add_node(101, labels=["0"])
snm_dummy_graph_2.add_node(102, labels=["0"])
snm_dummy_graph_2.add_node(103, labels=["0"])
snm_dummy_graph_2.add_node(104, labels=["0"])
snm_dummy_graph_2.add_node(105, labels=["0"])
snm_dummy_graph_2.add_node(106, labels=["0"])
snm_dummy_graph_2.add_node(107, labels=["0"])
snm_dummy_graph_2.add_node(108, labels=["0"])
snm_dummy_graph_2.add_node(109, labels=["0"])
snm_dummy_graph_2.add_edge(100, 24, label="n")
snm_dummy_graph_2.add_edge(100, 25, label="n")
snm_dummy_graph_2.add_edge(100, 101, label="n")
snm_dummy_graph_2.add_edge(101, 102, label="n")
snm_dummy_graph_2.add_edge(101, 103, label="n")
snm_dummy_graph_2.add_edge(102, 103, label="n")
snm_dummy_graph_2.add_edge(102, 104, label="n")
snm_dummy_graph_2.add_edge(103, 105, label="n")
snm_dummy_graph_2.add_edge(104, 105, label="n")
snm_dummy_graph_2.add_edge(104, 106, label="n")
snm_dummy_graph_2.add_edge(105, 107, label="n")
snm_dummy_graph_2.add_edge(106, 107, label="n")
snm_dummy_graph_2.add_edge(106, 108, label="n")
snm_dummy_graph_2.add_edge(107, 108, label="n")
snm_dummy_graph_2.add_edge(108, 109, label="n")
snm_dummy_graph_2.add_edge(109, 24, label="n")
snm_dummy_graph_2.add_edge(109, 25, label="n")
# rule 5.2.4
snm_dummy_graph_2.add_node(121, labels=["0"])
snm_dummy_graph_2.add_node(122, labels=["0"])
snm_dummy_graph_2.add_node(123, labels=["0"])
snm_dummy_graph_2.add_node(124, labels=["0"])
snm_dummy_graph_2.add_node(125, labels=["0"])
snm_dummy_graph_2.add_node(126, labels=["0"])
snm_dummy_graph_2.add_node(127, labels=["0"])
snm_dummy_graph_2.add_node(128, labels=["0"])
snm_dummy_graph_2.add_edge(121, 22, label="n")
snm_dummy_graph_2.add_edge(121, 122, label="n")
snm_dummy_graph_2.add_edge(121, 123, label="n")
snm_dummy_graph_2.add_edge(122, 123, label="n")
snm_dummy_graph_2.add_edge(122, 124, label="n")
snm_dummy_graph_2.add_edge(123, 124, label="n")
snm_dummy_graph_2.add_edge(124, 125, label="n")
snm_dummy_graph_2.add_edge(125, 126, label="n")
snm_dummy_graph_2.add_edge(125, 127, label="n")
snm_dummy_graph_2.add_edge(126, 127, label="n")
snm_dummy_graph_2.add_edge(126, 128, label="n")
snm_dummy_graph_2.add_edge(127, 128, label="n")
snm_dummy_graph_2.add_edge(128, 23, label="n")
# rule 5.1.3.2 # TODO: No idea how such a feature looks like
# /-------------------------------------------------------

# --------------------------------------------------------
snm_dummy_graph_features_2 = []

# ring
snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(2, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["r"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["r"])
snm_dummy_graph_features_2[-1].add_edge(3, 2, label="g")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(4, 5, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 5, label="g")
snm_dummy_graph_features_2[-1].add_edge(6, 7, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["r"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_edge(2, 1, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 2, label="g")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(4, 5, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 5, label="g")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["r"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(9, labels=["b"])
snm_dummy_graph_features_2[-1].add_edge(2, 1, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 2, label="g")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(4, 5, label="n")
snm_dummy_graph_features_2[-1].add_edge(9, 1, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["r"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(9, labels=["b"])
snm_dummy_graph_features_2[-1].add_edge(2, 1, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 2, label="g")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(9, 8, label="g")
snm_dummy_graph_features_2[-1].add_edge(9, 1, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["r"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(9, labels=["b"])
snm_dummy_graph_features_2[-1].add_edge(2, 1, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 2, label="g")
snm_dummy_graph_features_2[-1].add_edge(7, 8, label="n")
snm_dummy_graph_features_2[-1].add_edge(9, 8, label="g")
snm_dummy_graph_features_2[-1].add_edge(9, 1, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["r"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(9, labels=["b"])
snm_dummy_graph_features_2[-1].add_edge(2, 1, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(7, 8, label="n")
snm_dummy_graph_features_2[-1].add_edge(9, 8, label="g")
snm_dummy_graph_features_2[-1].add_edge(9, 1, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["r"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(9, labels=["b"])
snm_dummy_graph_features_2[-1].add_edge(6, 5, label="g")
snm_dummy_graph_features_2[-1].add_edge(6, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(7, 8, label="n")
snm_dummy_graph_features_2[-1].add_edge(9, 8, label="g")
snm_dummy_graph_features_2[-1].add_edge(9, 1, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(4, labels=["r"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["r"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(9, labels=["b"])
snm_dummy_graph_features_2[-1].add_edge(4, 5, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 5, label="g")
snm_dummy_graph_features_2[-1].add_edge(6, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(7, 8, label="n")
snm_dummy_graph_features_2[-1].add_edge(9, 8, label="g")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(3, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["r"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["r"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["b"])
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(4, 5, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 5, label="g")
snm_dummy_graph_features_2[-1].add_edge(6, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(7, 8, label="n")

# chain
snm_dummy_graph_features_2 += snm_dummy_graph_features_2[6:] + snm_dummy_graph_features_2[:2]

# other
snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["G"])
snm_dummy_graph_features_2[-1].add_edge(1, 2, label="n")

# buddy
buddy_feature = nx.MultiDiGraph()
buddy_feature.add_node(1, labels=["0"])
buddy_feature.add_node(2, labels=["0"])
buddy_feature.add_node(3, labels=["0"])
buddy_feature.add_node(4, labels=["0"])
buddy_feature.add_node(5, labels=["0"])
buddy_feature.add_node(6, labels=["0"])
buddy_feature.add_edge(1, 4, label="n")
buddy_feature.add_edge(1, 5, label="n")
buddy_feature.add_edge(1, 6, label="n")
buddy_feature.add_edge(2, 4, label="n")
buddy_feature.add_edge(2, 5, label="n")
buddy_feature.add_edge(2, 6, label="n")
buddy_feature.add_edge(3, 4, label="n")
buddy_feature.add_edge(3, 5, label="n")
buddy_feature.add_edge(3, 6, label="n")
for i in range(20):
    snm_dummy_graph_features_2.append(buddy_feature)

# other
snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["0"])

# cube
snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(0, labels=["G"]) # hub
snm_dummy_graph_features_2[-1].add_node(1, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["G"])
snm_dummy_graph_features_2[-1].add_edge(0, 1, label="n")
snm_dummy_graph_features_2[-1].add_edge(0, 2, label="n")
snm_dummy_graph_features_2[-1].add_edge(0, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(1, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(1, 6, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 5, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 5, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 6, label="n")

#other
snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["G"])

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["G"])
snm_dummy_graph_features_2[-1].add_edge(1, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")

# wheel
for feature in snm_dummy_graph_features_2[4:0:-1] + snm_dummy_graph_features_2[0:1] + snm_dummy_graph_features_2[8:4:-1]:
    snm_dummy_graph_features_2.append(feature.copy())
    snm_dummy_graph_features_2[-1].add_node(10, labels=["G"])
    for node in snm_dummy_graph_features_2[-1].nodes_iter():
        if node != 10:
            snm_dummy_graph_features_2[-1].add_edge(10, node, label="n")

# TODO: rules 5.2.2.0 and 5.2.4.0
for i in range(294):
    snm_dummy_graph_features_2.append(nx.MultiDiGraph())

# other
snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(1, 2, label="n")
snm_dummy_graph_features_2[-1].add_edge(1, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 5, label="n")
snm_dummy_graph_features_2[-1].add_edge(4, 5, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(4, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(4, 5, label="n")
snm_dummy_graph_features_2[-1].add_edge(4, 6, label="n")
snm_dummy_graph_features_2[-1].add_edge(5, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 8, label="n")
snm_dummy_graph_features_2[-1].add_edge(7, 8, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(1, 2, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["G"])
snm_dummy_graph_features_2[-1].add_edge(1, 2, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 5, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["G"])
snm_dummy_graph_features_2[-1].add_edge(1, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(4, 5, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(1, 2, label="n")
# /-------------------------------------------------------
