'''
Created on Jan 21, 2016

@author: Ivan Ivanov
'''

import networkx as nx

##################################################
# For test_graph
##################################################
gt_dummy_graph = nx.MultiDiGraph()
gt_dummy_graph.add_node(1, labels = ["1"])
gt_dummy_graph.add_node(2, labels = ["2"])
gt_dummy_graph.add_node(3, labels = ["3"])
gt_dummy_graph.add_node(4, labels = ["4"])
gt_dummy_graph.add_node(5, labels = ["5"])
gt_dummy_graph.add_node(6, labels = ["6"])
gt_dummy_graph.add_node(7, labels = ["7"])
gt_dummy_graph.add_node(8, labels = ["8"])
gt_dummy_graph.add_node(9, labels = ["9"])
gt_dummy_graph.add_node(10, labels = ["10"])
gt_dummy_graph.add_node(11, labels = ["11"])
gt_dummy_graph.add_node(12, labels = ["12"])
gt_dummy_graph.add_node(13, labels = ["13"])
gt_dummy_graph.add_node(14, labels = ["14"])
gt_dummy_graph.add_node(15, labels = ["15"])
gt_dummy_graph.add_node(16, labels = ["16"])
gt_dummy_graph.add_edge(1, 2, label = "0")
gt_dummy_graph.add_edge(1, 3, label = "0")
gt_dummy_graph.add_edge(1, 5, label = "0")
gt_dummy_graph.add_edge(1, 6, label = "0")
gt_dummy_graph.add_edge(1, 7, label = "0")
gt_dummy_graph.add_edge(1, 9, label = "0")
gt_dummy_graph.add_edge(1, 14, label = "0")
gt_dummy_graph.add_edge(1, 15, label = "0")
gt_dummy_graph.add_edge(1, 16, label = "0")
gt_dummy_graph.add_edge(2, 12, label = "0")
gt_dummy_graph.add_edge(2, 13, label = "0")
gt_dummy_graph.add_edge(3, 4, label = "0")
gt_dummy_graph.add_edge(3, 10, label = "0")
gt_dummy_graph.add_edge(3, 11, label = "0")
gt_dummy_graph.add_edge(3, 12, label = "0")
gt_dummy_graph.add_edge(4, 7, label = "0")
gt_dummy_graph.add_edge(4, 8, label = "0")
gt_dummy_graph.add_edge(5, 6, label = "0")
gt_dummy_graph.add_edge(5, 7, label = "0")
gt_dummy_graph.add_edge(5, 9, label = "0")
gt_dummy_graph.add_edge(5, 16, label = "0")
gt_dummy_graph.add_edge(6, 10, label = "0")
gt_dummy_graph.add_edge(6, 16, label = "0")
gt_dummy_graph.add_edge(7, 8, label = "0")
gt_dummy_graph.add_edge(8, 9, label = "0")
gt_dummy_graph.add_edge(10, 11, label = "0")
gt_dummy_graph.add_edge(11, 12, label = "0")
gt_dummy_graph.add_edge(11, 13, label = "0")
gt_dummy_graph.add_edge(12, 14, label = "0")
gt_dummy_graph.add_edge(12, 15, label = "0")
gt_dummy_graph.add_edge(13, 14, label = "0")
gt_dummy_graph.add_edge(13, 15, label = "0")
# /-------------------------------------------------------

# --------------------------------------------------------
gt_dummy_subgraph = nx.MultiDiGraph()
gt_dummy_subgraph.add_node(1, labels = ["1"])
gt_dummy_subgraph.add_node(6, labels = ["6"])
gt_dummy_subgraph.add_node(9, labels = ["9"])
gt_dummy_subgraph.add_node(10, labels = ["10"])
gt_dummy_subgraph.add_edge(1, 6, label = "0")
gt_dummy_subgraph.add_edge(1, 9, label = "0")
gt_dummy_subgraph.add_edge(6, 10, label = "0")
# /-------------------------------------------------------

# --------------------------------------------------------
# r-ball: center=10, r=2, edge_dir=0
gt_dummy_rball_10_r2_all = nx.MultiDiGraph()
gt_dummy_rball_10_r2_all.add_node(10, labels = ["10"]) # center
gt_dummy_rball_10_r2_all.add_node(1, labels = ["1"])
gt_dummy_rball_10_r2_all.add_node(3, labels = ["3"])
gt_dummy_rball_10_r2_all.add_node(4, labels = ["4"])
gt_dummy_rball_10_r2_all.add_node(5, labels = ["5"])
gt_dummy_rball_10_r2_all.add_node(6, labels = ["6"])
gt_dummy_rball_10_r2_all.add_node(11, labels = ["11"])
gt_dummy_rball_10_r2_all.add_node(12, labels = ["12"])
gt_dummy_rball_10_r2_all.add_node(13, labels = ["13"])
gt_dummy_rball_10_r2_all.add_node(16, labels = ["16"])
gt_dummy_rball_10_r2_all.add_edge(1, 3, label = "0")
gt_dummy_rball_10_r2_all.add_edge(1, 6, label = "0")
gt_dummy_rball_10_r2_all.add_edge(3, 4, label = "0")
gt_dummy_rball_10_r2_all.add_edge(3, 10, label = "0")
gt_dummy_rball_10_r2_all.add_edge(3, 11, label = "0")
gt_dummy_rball_10_r2_all.add_edge(3, 12, label = "0")
gt_dummy_rball_10_r2_all.add_edge(5, 6, label = "0")
gt_dummy_rball_10_r2_all.add_edge(6, 10, label = "0")
gt_dummy_rball_10_r2_all.add_edge(6, 16, label = "0")
gt_dummy_rball_10_r2_all.add_edge(10, 11, label = "0")
gt_dummy_rball_10_r2_all.add_edge(11, 12, label = "0")
gt_dummy_rball_10_r2_all.add_edge(11, 13, label = "0")
# /-------------------------------------------------------

# --------------------------------------------------------
# r-ball: center=10, r=2, edge_dir=1
gt_dummy_rball_10_r2_out = nx.MultiDiGraph()
gt_dummy_rball_10_r2_out.add_node(10, labels = ["10"]) # center
gt_dummy_rball_10_r2_out.add_node(11, labels = ["11"])
gt_dummy_rball_10_r2_out.add_node(12, labels = ["12"])
gt_dummy_rball_10_r2_out.add_node(13, labels = ["13"])
gt_dummy_rball_10_r2_out.add_edge(10, 11, label = "0")
gt_dummy_rball_10_r2_out.add_edge(11, 12, label = "0")
gt_dummy_rball_10_r2_out.add_edge(11, 13, label = "0")
# /-------------------------------------------------------

# --------------------------------------------------------
# r-ball: center=10, r=2, edge_dir=-1
gt_dummy_rball_10_r2_in = nx.MultiDiGraph()
gt_dummy_rball_10_r2_in.add_node(10, labels = ["10"]) # center
gt_dummy_rball_10_r2_in.add_node(1, labels = ["1"])
gt_dummy_rball_10_r2_in.add_node(3, labels = ["3"])
gt_dummy_rball_10_r2_in.add_node(5, labels = ["5"])
gt_dummy_rball_10_r2_in.add_node(6, labels = ["6"])
gt_dummy_rball_10_r2_in.add_edge(1, 3, label = "0")
gt_dummy_rball_10_r2_in.add_edge(1, 6, label = "0")
gt_dummy_rball_10_r2_in.add_edge(3, 10, label = "0")
gt_dummy_rball_10_r2_in.add_edge(5, 6, label = "0")
gt_dummy_rball_10_r2_in.add_edge(6, 10, label = "0")
# /-------------------------------------------------------

# --------------------------------------------------------
gt_dummy_colored_expected = nx.MultiDiGraph()
gt_dummy_colored_expected.add_node("1", labels=["4"])
gt_dummy_colored_expected.add_node("2", labels=["5", "6"])
gt_dummy_colored_expected.add_node("3", labels=["2", "3"])
gt_dummy_colored_expected.add_edge("1", "3", label="7")
# /-------------------------------------------------------

# --------------------------------------------------------
gt_dummy_wl = nx.MultiDiGraph()
gt_dummy_wl.add_node(1, labels=["0"])
gt_dummy_wl.add_node(2, labels=["1"])
gt_dummy_wl.add_node(3, labels=["0"])
gt_dummy_wl.add_node(4, labels=["1"])
gt_dummy_wl.add_node(5, labels=["0"])
gt_dummy_wl.add_edge(1, 2, label="a")
gt_dummy_wl.add_edge(2, 1, label="a")
gt_dummy_wl.add_edge(2, 3, label="a")
gt_dummy_wl.add_edge(3, 4, label="a")
gt_dummy_wl.add_edge(4, 1, label="a")
gt_dummy_wl.add_edge(4, 3, label="a")
gt_dummy_wl.add_edge(4, 5, label="b")
# /-------------------------------------------------------

##################################################
# For test_arnborg_prokurowski
##################################################
# Arnborg & Proskurowski example graph with tree-width 2
ap_graph_tw_2 = nx.MultiDiGraph()
ap_graph_tw_2.add_node(1, labels = ["(0)"])
ap_graph_tw_2.add_node(2, labels = ["(0)"])
ap_graph_tw_2.add_node(3, labels = ["(0)"])
ap_graph_tw_2.add_node(4, labels = ["(0)"])
ap_graph_tw_2.add_node(5, labels = ["(0)"])
ap_graph_tw_2.add_node(6, labels = ["(0)"])
ap_graph_tw_2.add_node(7, labels = ["(0)"])
ap_graph_tw_2.add_node(8, labels = ["(0)"])
ap_graph_tw_2.add_node(9, labels = ["(0)"])
ap_graph_tw_2.add_node(10, labels = ["(0)"])
ap_graph_tw_2.add_node(11, labels = ["(0)"])
ap_graph_tw_2.add_node(12, labels = ["(0)"])
ap_graph_tw_2.add_node(13, labels = ["(0)"])
ap_graph_tw_2.add_node(14, labels = ["(0)"])
ap_graph_tw_2.add_node(15, labels = ["(0)"])
ap_graph_tw_2.add_edge(1, 13, label = "0")
ap_graph_tw_2.add_edge(2, 13, label = "0")
ap_graph_tw_2.add_edge(2, 14, label = "0")
ap_graph_tw_2.add_edge(3, 14, label = "0")
ap_graph_tw_2.add_edge(4, 15, label = "0")
ap_graph_tw_2.add_edge(5, 6, label = "0")
ap_graph_tw_2.add_edge(5, 15, label = "0")
ap_graph_tw_2.add_edge(6, 5, label = "0")
ap_graph_tw_2.add_edge(6, 7, label = "0")
ap_graph_tw_2.add_edge(7, 6, label = "0")
ap_graph_tw_2.add_edge(7, 15, label = "0")
ap_graph_tw_2.add_edge(8, 12, label = "0")
ap_graph_tw_2.add_edge(9, 10, label = "0")
ap_graph_tw_2.add_edge(9, 12, label = "0")
ap_graph_tw_2.add_edge(10, 9, label = "0")
ap_graph_tw_2.add_edge(10, 11, label = "0")
ap_graph_tw_2.add_edge(11, 10, label = "0")
ap_graph_tw_2.add_edge(11, 12, label = "0")
ap_graph_tw_2.add_edge(12, 8, label = "0")
ap_graph_tw_2.add_edge(12, 9, label = "0")
ap_graph_tw_2.add_edge(12, 11, label = "0")
ap_graph_tw_2.add_edge(12, 13, label = "0")
ap_graph_tw_2.add_edge(12, 15, label = "0")
ap_graph_tw_2.add_edge(13, 1, label = "0")
ap_graph_tw_2.add_edge(13, 2, label = "0")
ap_graph_tw_2.add_edge(13, 12, label = "0")
ap_graph_tw_2.add_edge(13, 14, label = "0")
ap_graph_tw_2.add_edge(13, 15, label = "0")
ap_graph_tw_2.add_edge(14, 2, label = "0")
ap_graph_tw_2.add_edge(14, 3, label = "0")
ap_graph_tw_2.add_edge(14, 13, label = "0")
ap_graph_tw_2.add_edge(14, 15, label = "0")
ap_graph_tw_2.add_edge(15, 4, label = "0")
ap_graph_tw_2.add_edge(15, 5, label = "0")
ap_graph_tw_2.add_edge(15, 7, label = "0")
ap_graph_tw_2.add_edge(15, 12, label = "0")
ap_graph_tw_2.add_edge(15, 13, label = "0")
ap_graph_tw_2.add_edge(15, 14, label = "0")
# /-------------------------------------------------------

# --------------------------------------------------------
ap_ring_graph = nx.MultiDiGraph()
ap_ring_graph.add_node(1, labels=["1"])
ap_ring_graph.add_node(2, labels=["2"])
ap_ring_graph.add_node(3, labels=["3"])
ap_ring_graph.add_node(4, labels=["4"])
ap_ring_graph.add_node(5, labels=["5"])
ap_ring_graph.add_edge(1, 2, label="a")
ap_ring_graph.add_edge(2, 3, label="b")
ap_ring_graph.add_edge(3, 4, label="c")
ap_ring_graph.add_edge(4, 5, label="d")
ap_ring_graph.add_edge(5, 1, label="e")
# /-------------------------------------------------------

# --------------------------------------------------------
ap_graph_tw_3 = nx.MultiDiGraph()
# base structure
ap_graph_tw_3.add_node(201, labels=["base_1"])
ap_graph_tw_3.add_node(202, labels=["base_2"])
ap_graph_tw_3.add_node(203, labels=["base_3"])
ap_graph_tw_3.add_node(204, labels=["base_4"])
ap_graph_tw_3.add_edge(201, 202, label="0")
ap_graph_tw_3.add_edge(201, 203, label="0")
ap_graph_tw_3.add_edge(201, 204, label="0")
ap_graph_tw_3.add_edge(202, 203, label="0")
ap_graph_tw_3.add_edge(202, 204, label="0")
ap_graph_tw_3.add_edge(203, 204, label="0")
# rule 4.1
ap_graph_tw_3.add_node(1, labels=["1 (4.1)"])
ap_graph_tw_3.add_edge(1, 202, label="0")
ap_graph_tw_3.add_edge(1, 203, label="0")
ap_graph_tw_3.add_edge(1, 204, label="0")
# rule 4.2
ap_graph_tw_3.add_node(5, labels=["1 (4.2)"])
ap_graph_tw_3.add_node(6, labels=["2 (4.2)"])
ap_graph_tw_3.add_node(7, labels=["3 (4.2)"])
ap_graph_tw_3.add_node(8, labels=["4 (4.2)"])
ap_graph_tw_3.add_node(9, labels=["5 (4.2)"])
ap_graph_tw_3.add_edge(5, 7, label="0")
ap_graph_tw_3.add_edge(5, 8, label="0")
ap_graph_tw_3.add_edge(5, 9, label="0")
ap_graph_tw_3.add_edge(6, 7, label="0")
ap_graph_tw_3.add_edge(6, 8, label="0")
ap_graph_tw_3.add_edge(6, 9, label="0")
ap_graph_tw_3.add_edge(7, 201, label="0")
ap_graph_tw_3.add_edge(8, 202, label="0")
ap_graph_tw_3.add_edge(9, 203, label="0")
# rule 4.3
ap_graph_tw_3.add_node(220, labels=["0"])
ap_graph_tw_3.add_node(221, labels=["0"])
ap_graph_tw_3.add_node(222, labels=["0"])
ap_graph_tw_3.add_node(223, labels=["G"])
ap_graph_tw_3.add_node(230, labels=["0"])
ap_graph_tw_3.add_node(231, labels=["0"])
ap_graph_tw_3.add_node(232, labels=["0"])
ap_graph_tw_3.add_node(233, labels=["G"])
ap_graph_tw_3.add_node(240, labels=["0"])
ap_graph_tw_3.add_node(241, labels=["0"])
ap_graph_tw_3.add_node(242, labels=["0"])
ap_graph_tw_3.add_node(243, labels=["G"])
ap_graph_tw_3.add_edge(220, 221, label="n")
ap_graph_tw_3.add_edge(220, 222, label="n")
ap_graph_tw_3.add_edge(220, 223, label="n")
ap_graph_tw_3.add_edge(221, 222, label="n")
ap_graph_tw_3.add_edge(221, 223, label="n")
ap_graph_tw_3.add_edge(222, 223, label="n")
ap_graph_tw_3.add_edge(230, 231, label="n")
ap_graph_tw_3.add_edge(230, 232, label="n")
ap_graph_tw_3.add_edge(230, 233, label="n")
ap_graph_tw_3.add_edge(231, 232, label="n")
ap_graph_tw_3.add_edge(231, 233, label="n")
ap_graph_tw_3.add_edge(232, 233, label="n")
ap_graph_tw_3.add_edge(240, 241, label="n")
ap_graph_tw_3.add_edge(240, 242, label="n")
ap_graph_tw_3.add_edge(240, 243, label="n")
ap_graph_tw_3.add_edge(241, 242, label="n")
ap_graph_tw_3.add_edge(241, 243, label="n")
ap_graph_tw_3.add_edge(242, 243, label="n")
ap_graph_tw_3.add_node(250, labels=["G"]) # hub
ap_graph_tw_3.add_node(251, labels=["0"])
ap_graph_tw_3.add_node(252, labels=["0"])
ap_graph_tw_3.add_node(253, labels=["0"])
ap_graph_tw_3.add_edge(250, 251, label="n")
ap_graph_tw_3.add_edge(250, 252, label="n")
ap_graph_tw_3.add_edge(250, 253, label="n")
ap_graph_tw_3.add_edge(251, 223, label="n")
ap_graph_tw_3.add_edge(251, 243, label="n")
ap_graph_tw_3.add_edge(252, 223, label="n")
ap_graph_tw_3.add_edge(252, 233, label="n")
ap_graph_tw_3.add_edge(253, 233, label="n")
ap_graph_tw_3.add_edge(253, 243, label="n")
# rule 5.1.1
ap_graph_tw_3.add_node(17, labels=["1 (5.1.1)"])
ap_graph_tw_3.add_node(18, labels=["2 (5.1.1)"])
ap_graph_tw_3.add_node(19, labels=["3 (5.1.1)"])
ap_graph_tw_3.add_node(20, labels=["4 (5.1.1)"])
ap_graph_tw_3.add_edge(17, 18, label="0")
ap_graph_tw_3.add_edge(17, 19, label="0")
ap_graph_tw_3.add_edge(17, 20, label="0")
ap_graph_tw_3.add_edge(18, 19, label="0")
ap_graph_tw_3.add_edge(18, 20, label="0")
ap_graph_tw_3.add_edge(19, 20, label="0")
# rule 5.1.2
ap_graph_tw_3.add_node(21, labels=["1 (5.1.2)"])
ap_graph_tw_3.add_node(22, labels=["2 (5.1.2)"])
ap_graph_tw_3.add_node(23, labels=["3 (5.1.2)"])
ap_graph_tw_3.add_node(24, labels=["4 (5.1.2)"])
ap_graph_tw_3.add_edge(21, 22, label="0")
ap_graph_tw_3.add_edge(21, 23, label="0")
ap_graph_tw_3.add_edge(21, 24, label="0")
ap_graph_tw_3.add_edge(22, 23, label="0")
ap_graph_tw_3.add_edge(22, 24, label="0")
ap_graph_tw_3.add_edge(23, 201, label="0")
ap_graph_tw_3.add_edge(24, 202, label="0")
ap_graph_tw_3.add_edge(23, 202, label="0")
ap_graph_tw_3.add_edge(24, 201, label="0")
# rule 5.2.1 - 1
ap_graph_tw_3.add_node(31, labels=["1 (5.2.1 - 1)"])
ap_graph_tw_3.add_node(32, labels=["2 (5.2.1 - 1)"])
ap_graph_tw_3.add_edge(31, 32, label="0")
ap_graph_tw_3.add_edge(31, 202, label="0")
ap_graph_tw_3.add_edge(31, 203, label="0")
ap_graph_tw_3.add_edge(32, 202, label="0")
ap_graph_tw_3.add_edge(32, 204, label="0")
# # rule 5.2.1 - 2 # This configuration is not safely reducible
# ap_graph_tw_3.add_node(41, labels=["1 (5.2.1 - 2)"])
# ap_graph_tw_3.add_node(42, labels=["2 (5.2.1 - 2)"])
# ap_graph_tw_3.add_edge(41, 42, label="0")
# ap_graph_tw_3.add_edge(41, 201, label="0")
# ap_graph_tw_3.add_edge(41, 202, label="0")
# ap_graph_tw_3.add_edge(42, 203, label="0")
# ap_graph_tw_3.add_edge(42, 204, label="0")
# rule 5.2.2
ap_graph_tw_3.add_node(51, labels=["1 (5.2.2)"])
ap_graph_tw_3.add_node(52, labels=["2 (5.2.2)"])
ap_graph_tw_3.add_node(53, labels=["3 (5.2.2)"])
ap_graph_tw_3.add_node(54, labels=["4 (5.2.2)"])
ap_graph_tw_3.add_edge(51, 52, label="0")
ap_graph_tw_3.add_edge(51, 53, label="0")
ap_graph_tw_3.add_edge(51, 204, label="0")
ap_graph_tw_3.add_edge(52, 54, label="0")
ap_graph_tw_3.add_edge(52, 204, label="0")
ap_graph_tw_3.add_edge(53, 204, label="0")
ap_graph_tw_3.add_edge(54, 204, label="0")
ap_graph_tw_3.add_edge(53, 202, label="0")
ap_graph_tw_3.add_edge(54, 203, label="0")
# rule 5.2.3.1
ap_graph_tw_3.add_node(60, labels=["0 (5.2.3.1)"])
ap_graph_tw_3.add_node(61, labels=["1 (5.2.3.1)"])
ap_graph_tw_3.add_node(62, labels=["2 (5.2.3.1)"])
ap_graph_tw_3.add_node(63, labels=["3 (5.2.3.1)"])
ap_graph_tw_3.add_node(64, labels=["4 (5.2.3.1)"])
ap_graph_tw_3.add_node(65, labels=["5 (5.2.3.1)"])
ap_graph_tw_3.add_edge(60, 61, label="0")
ap_graph_tw_3.add_edge(60, 62, label="0")
ap_graph_tw_3.add_edge(60, 63, label="0")
ap_graph_tw_3.add_edge(60, 64, label="0")
ap_graph_tw_3.add_edge(60, 65, label="0")
ap_graph_tw_3.add_edge(61, 62, label="0")
ap_graph_tw_3.add_edge(62, 63, label="0")
ap_graph_tw_3.add_edge(63, 64, label="0")
ap_graph_tw_3.add_edge(64, 65, label="0")
ap_graph_tw_3.add_edge(65, 61, label="0")
# # rule 5.2.3.2 # TODO: not sure what is this configuration
# ap_graph_tw_3.add_node(, labels=[" (5.2.3.2)"])
# ap_graph_tw_3.add_edge(, , label="0")
# rule 5.2.3.3
ap_graph_tw_3.add_node(81, labels=["1 (5.2.3.3)"])
ap_graph_tw_3.add_node(82, labels=["2 (5.2.3.3)"])
ap_graph_tw_3.add_node(83, labels=["3 (5.2.3.3)"])
ap_graph_tw_3.add_node(84, labels=["4 (5.2.3.3)"])
ap_graph_tw_3.add_edge(81, 82, label="0")
ap_graph_tw_3.add_edge(81, 83, label="0")
ap_graph_tw_3.add_edge(81, 201, label="0")
ap_graph_tw_3.add_edge(82, 84, label="0")
ap_graph_tw_3.add_edge(82, 202, label="0")
ap_graph_tw_3.add_edge(83, 84, label="0")
ap_graph_tw_3.add_edge(83, 201, label="0")
ap_graph_tw_3.add_edge(84, 202, label="0")
# rule 5.2.4
ap_graph_tw_3.add_node(121, labels=["0"])
ap_graph_tw_3.add_node(122, labels=["0"])
ap_graph_tw_3.add_node(123, labels=["0"])
ap_graph_tw_3.add_node(124, labels=["0"])
ap_graph_tw_3.add_node(125, labels=["0"])
ap_graph_tw_3.add_node(126, labels=["0"])
ap_graph_tw_3.add_node(127, labels=["0"])
ap_graph_tw_3.add_node(128, labels=["0"])
ap_graph_tw_3.add_edge(121, 141, label="n")
ap_graph_tw_3.add_edge(121, 122, label="n")
ap_graph_tw_3.add_edge(121, 123, label="n")
ap_graph_tw_3.add_edge(122, 123, label="n")
ap_graph_tw_3.add_edge(122, 124, label="n")
ap_graph_tw_3.add_edge(123, 124, label="n")
ap_graph_tw_3.add_edge(124, 125, label="n")
ap_graph_tw_3.add_edge(125, 126, label="n")
ap_graph_tw_3.add_edge(125, 127, label="n")
ap_graph_tw_3.add_edge(126, 127, label="n")
ap_graph_tw_3.add_edge(126, 128, label="n")
ap_graph_tw_3.add_edge(127, 128, label="n")
ap_graph_tw_3.add_edge(128, 142, label="n")
# rule 5.2.5
ap_graph_tw_3.add_node(131, labels=["1 (5.2.5)"])
ap_graph_tw_3.add_node(132, labels=["2 (5.2.5)"])
ap_graph_tw_3.add_node(133, labels=["3 (5.2.5)"])
ap_graph_tw_3.add_node(134, labels=["4 (5.2.5)"])
ap_graph_tw_3.add_node(135, labels=["5 (5.2.5)"])
ap_graph_tw_3.add_node(136, labels=["6 (5.2.5)"])
ap_graph_tw_3.add_edge(131, 132, label="0")
ap_graph_tw_3.add_edge(131, 133, label="0")
ap_graph_tw_3.add_edge(131, 134, label="0")
ap_graph_tw_3.add_edge(132, 133, label="0")
ap_graph_tw_3.add_edge(132, 135, label="0")
ap_graph_tw_3.add_edge(133, 136, label="0")
ap_graph_tw_3.add_edge(134, 135, label="0")
ap_graph_tw_3.add_edge(134, 136, label="0")
ap_graph_tw_3.add_edge(135, 136, label="0")
# rule 6.1
ap_graph_tw_3.add_node(141, labels=["1 (6.1)"])
ap_graph_tw_3.add_node(142, labels=["2 (6.1)"])
ap_graph_tw_3.add_node(143, labels=["3 (6.1)"])
ap_graph_tw_3.add_node(144, labels=["4 (6.1)"])
ap_graph_tw_3.add_node(145, labels=["5 (6.1)"])
ap_graph_tw_3.add_node(146, labels=["6 (6.1)"])
ap_graph_tw_3.add_edge(141, 142, label="0")
ap_graph_tw_3.add_edge(141, 144, label="0")
ap_graph_tw_3.add_edge(141, 146, label="0")
ap_graph_tw_3.add_edge(142, 143, label="0")
ap_graph_tw_3.add_edge(142, 145, label="0")
ap_graph_tw_3.add_edge(143, 144, label="0")
ap_graph_tw_3.add_edge(143, 146, label="0")
ap_graph_tw_3.add_edge(144, 145, label="0")
ap_graph_tw_3.add_edge(145, 146, label="0")
# rule 6.2
ap_graph_tw_3.add_node(151, labels=["1 (6.2)"])
ap_graph_tw_3.add_node(152, labels=["2 (6.2)"])
ap_graph_tw_3.add_node(154, labels=["4 (6.2)"])
ap_graph_tw_3.add_node(155, labels=["5 (6.2)"])
ap_graph_tw_3.add_edge(151, 152, label="0")
ap_graph_tw_3.add_edge(151, 154, label="0")
ap_graph_tw_3.add_edge(151, 204, label="0")
ap_graph_tw_3.add_edge(152, 203, label="0")
ap_graph_tw_3.add_edge(152, 155, label="0")
ap_graph_tw_3.add_edge(203, 154, label="0")
ap_graph_tw_3.add_edge(154, 155, label="0")
ap_graph_tw_3.add_edge(155, 204, label="0")
# rule 7.1
ap_graph_tw_3.add_node(161, labels=["1 (7.1)"])
ap_graph_tw_3.add_node(162, labels=["2 (7.1)"])
ap_graph_tw_3.add_node(163, labels=["3 (7.1)"])
ap_graph_tw_3.add_node(164, labels=["4 (7.1)"])
ap_graph_tw_3.add_node(165, labels=["5 (7.1)"])
ap_graph_tw_3.add_node(166, labels=["6 (7.1)"])
ap_graph_tw_3.add_node(167, labels=["7 (7.1)"])
ap_graph_tw_3.add_node(168, labels=["8 (7.1)"])
ap_graph_tw_3.add_edge(161, 162, label="0")
ap_graph_tw_3.add_edge(161, 163, label="0")
ap_graph_tw_3.add_edge(161, 165, label="0")
ap_graph_tw_3.add_edge(162, 164, label="0")
ap_graph_tw_3.add_edge(162, 166, label="0")
ap_graph_tw_3.add_edge(163, 164, label="0")
ap_graph_tw_3.add_edge(163, 167, label="0")
ap_graph_tw_3.add_edge(164, 168, label="0")
ap_graph_tw_3.add_edge(165, 166, label="0")
ap_graph_tw_3.add_edge(165, 167, label="0")
ap_graph_tw_3.add_edge(166, 168, label="0")
ap_graph_tw_3.add_edge(167, 168, label="0")
# rule 7.2 # TODO: reduced as 7.1 because it has lower priority
ap_graph_tw_3.add_node(171, labels=["1 (7.2)"])
ap_graph_tw_3.add_node(172, labels=["2 (7.2)"])
ap_graph_tw_3.add_node(173, labels=["3 (7.2)"])
ap_graph_tw_3.add_node(175, labels=["5 (7.2)"])
ap_graph_tw_3.add_node(176, labels=["6 (7.2)"])
ap_graph_tw_3.add_node(177, labels=["7 (7.2)"])
ap_graph_tw_3.add_edge(171, 172, label="0")
ap_graph_tw_3.add_edge(171, 173, label="0")
ap_graph_tw_3.add_edge(171, 175, label="0")
ap_graph_tw_3.add_edge(172, 202, label="0")
ap_graph_tw_3.add_edge(172, 176, label="0")
ap_graph_tw_3.add_edge(173, 202, label="0")
ap_graph_tw_3.add_edge(173, 177, label="0")
ap_graph_tw_3.add_edge(175, 176, label="0")
ap_graph_tw_3.add_edge(175, 177, label="0")
ap_graph_tw_3.add_edge(176, 203, label="0")
ap_graph_tw_3.add_edge(177, 203, label="0")
# /-------------------------------------------------------

##################################################
# For test_similar_nodes_mining
##################################################
snm_dummy_graph = nx.MultiDiGraph()
snm_dummy_graph.add_node(1, labels=["r"])
snm_dummy_graph.add_node(2, labels=["r"])
snm_dummy_graph.add_node(3, labels=["r"])
snm_dummy_graph.add_node(4, labels=["b"])
snm_dummy_graph.add_node(5, labels=["r"])
snm_dummy_graph.add_node(6, labels=["b"])
snm_dummy_graph.add_node(7, labels=["b"])
snm_dummy_graph.add_node(8, labels=["b", "r"])
snm_dummy_graph.add_node(9, labels=["r"])
snm_dummy_graph.add_node(10, labels=["b"])
snm_dummy_graph.add_node(11, labels=["b", "r"])
snm_dummy_graph.add_node(12, labels=["b", "r"])
snm_dummy_graph.add_edge(1, 8, label="g")
snm_dummy_graph.add_edge(2, 1, label="n")
snm_dummy_graph.add_edge(2, 3, label="g")
snm_dummy_graph.add_edge(3, 5, label="n")
snm_dummy_graph.add_edge(3, 6, label="n")
snm_dummy_graph.add_edge(4, 3, label="g")
snm_dummy_graph.add_edge(6, 2, label="n")
snm_dummy_graph.add_edge(7, 2, label="n")
snm_dummy_graph.add_edge(8, 7, label="n")
snm_dummy_graph.add_edge(8, 9, label="n")
snm_dummy_graph.add_edge(10, 8, label="g")
snm_dummy_graph.add_edge(11, 1, label="n")
snm_dummy_graph.add_edge(11, 12, label="n")

snm_dummy_graph_features = []

snm_dummy_graph_features.append(nx.MultiDiGraph())
snm_dummy_graph_features[-1].add_node("n_2", labels=["r"])
snm_dummy_graph_features[-1].add_node("n_1", labels=["r"])
snm_dummy_graph_features[-1].add_edge("n_2", "n_1", label="n")

snm_dummy_graph_features.append(nx.MultiDiGraph())
snm_dummy_graph_features[-1].add_node("n_2", labels=["r"])
snm_dummy_graph_features[-1].add_node("n_3", labels=["r"])
snm_dummy_graph_features[-1].add_edge("n_2", "n_3", label="g")

snm_dummy_graph_features.append(nx.MultiDiGraph())
snm_dummy_graph_features[-1].add_node("n_2", labels=["wl_1.3"])
snm_dummy_graph_features[-1].add_node("n_1", labels=["wl_1.2"])
snm_dummy_graph_features[-1].add_edge("n_2", "n_1", label="wl_1.1")

snm_dummy_graph_features.append(nx.MultiDiGraph())
snm_dummy_graph_features[-1].add_node("n_2", labels=["wl_1.3"])
snm_dummy_graph_features[-1].add_node("n_3", labels=["wl_1.4"])
snm_dummy_graph_features[-1].add_edge("n_2", "n_3", label="wl_1.0")

snm_dummy_graph_features.append(nx.MultiDiGraph())
snm_dummy_graph_features[-1].add_node("n_2", labels=["r"])
snm_dummy_graph_features[-1].add_node("n_6", labels=["b"])
snm_dummy_graph_features[-1].add_edge("n_6", "n_2", label="n")

snm_dummy_graph_features.append(nx.MultiDiGraph())
snm_dummy_graph_features[-1].add_node("n_2", labels=["r"])
snm_dummy_graph_features[-1].add_node("n_7", labels=["b"])
snm_dummy_graph_features[-1].add_edge("n_7", "n_2", label="n")

snm_dummy_graph_features.append(nx.MultiDiGraph())
snm_dummy_graph_features[-1].add_node("n_2", labels=["wl_1.7"])
snm_dummy_graph_features[-1].add_node("n_6", labels=["wl_1.6"])
snm_dummy_graph_features[-1].add_edge("n_6", "n_2", label="wl_1.5")

snm_dummy_graph_features.append(nx.MultiDiGraph())
snm_dummy_graph_features[-1].add_node("n_2", labels=["wl_1.7"])
snm_dummy_graph_features[-1].add_node("n_7", labels=["wl_1.6"])
snm_dummy_graph_features[-1].add_edge("n_7", "n_2", label="wl_1.5")
# /-------------------------------------------------------

# --------------------------------------------------------
snm_dummy_feature = nx.MultiDiGraph()
snm_dummy_feature.add_node("n_1", labels=["1", "2"])
snm_dummy_feature.add_node("n_2", labels=["3"])
snm_dummy_feature.add_node("n_3", labels=["4", "5", "6"])
snm_dummy_feature.add_edge("n_1", "n_2", label="7")
snm_dummy_feature.add_edge("n_1", "n_2", label="8")
snm_dummy_feature.add_edge("n_3", "n_1", label="7")
snm_dummy_feature.add_edge("n_1", "n_3", label="7")
snm_dummy_feature.add_edge("n_3", "n_1", label="8")
# /-------------------------------------------------------

# --------------------------------------------------------
# graph containing all three types of features (fixed, pattern and dynamic)
snm_dummy_graph_2 = nx.MultiDiGraph()
# ring (2.2.0.0)
snm_dummy_graph_2.add_node(1, labels=["b", "r"])
snm_dummy_graph_2.add_node(2, labels=["b"])
snm_dummy_graph_2.add_node(3, labels=["b", "r"])
snm_dummy_graph_2.add_node(4, labels=["r"])
snm_dummy_graph_2.add_node(5, labels=["b"])
snm_dummy_graph_2.add_node(6, labels=["b", "r"])
snm_dummy_graph_2.add_node(7, labels=["r"])
snm_dummy_graph_2.add_node(8, labels=["b"])
snm_dummy_graph_2.add_node(9, labels=["b"])
snm_dummy_graph_2.add_edge(2, 1, label="n")
snm_dummy_graph_2.add_edge(3, 2, label="g")
snm_dummy_graph_2.add_edge(3, 4, label="n")
snm_dummy_graph_2.add_edge(4, 5, label="n")
snm_dummy_graph_2.add_edge(6, 5, label="g")
snm_dummy_graph_2.add_edge(6, 7, label="n")
snm_dummy_graph_2.add_edge(7, 8, label="n")
snm_dummy_graph_2.add_edge(9, 8, label="g")
snm_dummy_graph_2.add_edge(9, 1, label="n")
# auxiliary structure: cat's cradle (6.1.0.0)
snm_dummy_graph_2.add_node(21, labels=["G"])
snm_dummy_graph_2.add_node(22, labels=["G"])
snm_dummy_graph_2.add_node(23, labels=["G"])
snm_dummy_graph_2.add_node(24, labels=["G"])
snm_dummy_graph_2.add_node(25, labels=["G"])
snm_dummy_graph_2.add_node(26, labels=["G"])
snm_dummy_graph_2.add_edge(21, 22, label="n")
snm_dummy_graph_2.add_edge(21, 24, label="n")
snm_dummy_graph_2.add_edge(21, 26, label="n")
snm_dummy_graph_2.add_edge(22, 23, label="n")
snm_dummy_graph_2.add_edge(22, 25, label="n")
snm_dummy_graph_2.add_edge(23, 24, label="n")
snm_dummy_graph_2.add_edge(23, 26, label="n")
snm_dummy_graph_2.add_edge(24, 25, label="n")
snm_dummy_graph_2.add_edge(25, 26, label="n")
# chain (2.1.0.0)
snm_dummy_graph_2.add_node(11, labels=["b", "r"])
snm_dummy_graph_2.add_node(12, labels=["b"])
snm_dummy_graph_2.add_node(13, labels=["b", "r"])
snm_dummy_graph_2.add_node(14, labels=["r"])
snm_dummy_graph_2.add_node(15, labels=["b"])
snm_dummy_graph_2.add_node(16, labels=["b", "r"])
snm_dummy_graph_2.add_node(17, labels=["r"])
snm_dummy_graph_2.add_node(18, labels=["b"])
snm_dummy_graph_2.add_node(19, labels=["b"])
snm_dummy_graph_2.add_edge(11, 26, label="n")
snm_dummy_graph_2.add_edge(12, 11, label="n")
snm_dummy_graph_2.add_edge(13, 12, label="g")
snm_dummy_graph_2.add_edge(13, 14, label="n")
snm_dummy_graph_2.add_edge(14, 15, label="n")
snm_dummy_graph_2.add_edge(16, 15, label="g")
snm_dummy_graph_2.add_edge(16, 17, label="n")
snm_dummy_graph_2.add_edge(17, 18, label="n")
snm_dummy_graph_2.add_edge(19, 18, label="g")
snm_dummy_graph_2.add_edge(19, 11, label="n")
# cube (4.3.0.0)
snm_dummy_graph_2.add_node(50, labels=["G"]) # hub
snm_dummy_graph_2.add_node(51, labels=["0"])
snm_dummy_graph_2.add_node(52, labels=["0"])
snm_dummy_graph_2.add_node(53, labels=["0"])
snm_dummy_graph_2.add_edge(50, 51, label="n")
snm_dummy_graph_2.add_edge(50, 52, label="n")
snm_dummy_graph_2.add_edge(50, 53, label="n")
snm_dummy_graph_2.add_edge(51, 21, label="n")
snm_dummy_graph_2.add_edge(51, 25, label="n")
snm_dummy_graph_2.add_edge(52, 21, label="n")
snm_dummy_graph_2.add_edge(52, 23, label="n")
snm_dummy_graph_2.add_edge(53, 23, label="n")
snm_dummy_graph_2.add_edge(53, 25, label="n")
# buddy (4.2.0.0)
snm_dummy_graph_2.add_node(60, labels=["0"])
snm_dummy_graph_2.add_node(61, labels=["0"])
snm_dummy_graph_2.add_node(62, labels=["0"])
snm_dummy_graph_2.add_node(70, labels=["0"])
snm_dummy_graph_2.add_node(71, labels=["0"])
snm_dummy_graph_2.add_node(72, labels=["0"])
snm_dummy_graph_2.add_node(80, labels=["0"])
snm_dummy_graph_2.add_node(81, labels=["0"])
snm_dummy_graph_2.add_node(82, labels=["0"])
snm_dummy_graph_2.add_edge(70, 60, label="n")
snm_dummy_graph_2.add_edge(70, 61, label="n")
snm_dummy_graph_2.add_edge(70, 62, label="n")
snm_dummy_graph_2.add_edge(71, 60, label="n")
snm_dummy_graph_2.add_edge(71, 61, label="n")
snm_dummy_graph_2.add_edge(71, 62, label="n")
snm_dummy_graph_2.add_edge(72, 60, label="n")
snm_dummy_graph_2.add_edge(72, 61, label="n")
snm_dummy_graph_2.add_edge(72, 62, label="n")
snm_dummy_graph_2.add_edge(80, 60, label="n")
snm_dummy_graph_2.add_edge(80, 61, label="n")
snm_dummy_graph_2.add_edge(80, 62, label="n")
snm_dummy_graph_2.add_edge(81, 60, label="n")
snm_dummy_graph_2.add_edge(81, 61, label="n")
snm_dummy_graph_2.add_edge(81, 62, label="n")
snm_dummy_graph_2.add_edge(82, 60, label="n")
snm_dummy_graph_2.add_edge(82, 61, label="n")
snm_dummy_graph_2.add_edge(82, 62, label="n")
# wheel (5.2.3.1)
snm_dummy_graph_2.add_node(90, labels=["G"]) # center
snm_dummy_graph_2.add_node(91, labels=["b", "r"])
snm_dummy_graph_2.add_node(92, labels=["b"])
snm_dummy_graph_2.add_node(93, labels=["b", "r"])
snm_dummy_graph_2.add_node(94, labels=["r"])
snm_dummy_graph_2.add_node(95, labels=["b"])
snm_dummy_graph_2.add_node(96, labels=["b", "r"])
snm_dummy_graph_2.add_node(97, labels=["r"])
snm_dummy_graph_2.add_node(98, labels=["b"])
snm_dummy_graph_2.add_node(99, labels=["b"])
snm_dummy_graph_2.add_edge(90, 91, label="n")
snm_dummy_graph_2.add_edge(90, 92, label="n")
snm_dummy_graph_2.add_edge(90, 93, label="n")
snm_dummy_graph_2.add_edge(90, 94, label="n")
snm_dummy_graph_2.add_edge(90, 95, label="n")
snm_dummy_graph_2.add_edge(90, 96, label="n")
snm_dummy_graph_2.add_edge(90, 97, label="n")
snm_dummy_graph_2.add_edge(90, 98, label="n")
snm_dummy_graph_2.add_edge(90, 99, label="n")
snm_dummy_graph_2.add_edge(92, 91, label="n")
snm_dummy_graph_2.add_edge(93, 92, label="g")
snm_dummy_graph_2.add_edge(93, 94, label="n")
snm_dummy_graph_2.add_edge(94, 95, label="n")
snm_dummy_graph_2.add_edge(96, 95, label="g")
snm_dummy_graph_2.add_edge(96, 97, label="n")
snm_dummy_graph_2.add_edge(97, 98, label="n")
snm_dummy_graph_2.add_edge(99, 98, label="g")
snm_dummy_graph_2.add_edge(99, 91, label="n")
snm_dummy_graph_2.add_edge(90, 22, label="n") # keeps the auxiliary structure stable
snm_dummy_graph_2.add_edge(90, 23, label="n") # keeps the auxiliary structure stable
# rule 5.2.2 (turns into 5.2.4.0 after one reduction step)
snm_dummy_graph_2.add_node(100, labels=["0"])
snm_dummy_graph_2.add_node(101, labels=["0"])
snm_dummy_graph_2.add_node(102, labels=["0"])
snm_dummy_graph_2.add_node(103, labels=["0"])
snm_dummy_graph_2.add_node(104, labels=["0"])
snm_dummy_graph_2.add_node(105, labels=["0"])
snm_dummy_graph_2.add_node(106, labels=["0"])
snm_dummy_graph_2.add_node(107, labels=["0"])
snm_dummy_graph_2.add_node(108, labels=["0"])
snm_dummy_graph_2.add_node(109, labels=["0"])
snm_dummy_graph_2.add_edge(100, 24, label="n")
snm_dummy_graph_2.add_edge(100, 25, label="n")
snm_dummy_graph_2.add_edge(100, 101, label="n")
snm_dummy_graph_2.add_edge(101, 102, label="n")
snm_dummy_graph_2.add_edge(101, 103, label="n")
snm_dummy_graph_2.add_edge(102, 103, label="n")
snm_dummy_graph_2.add_edge(102, 104, label="n")
snm_dummy_graph_2.add_edge(103, 104, label="n")
snm_dummy_graph_2.add_edge(104, 105, label="n")
snm_dummy_graph_2.add_edge(105, 106, label="n")
snm_dummy_graph_2.add_edge(105, 107, label="n")
snm_dummy_graph_2.add_edge(106, 107, label="n")
snm_dummy_graph_2.add_edge(106, 108, label="n")
snm_dummy_graph_2.add_edge(107, 108, label="n")
snm_dummy_graph_2.add_edge(108, 109, label="n")
snm_dummy_graph_2.add_edge(109, 24, label="n")
snm_dummy_graph_2.add_edge(109, 25, label="n")
# rule 5.1.3.2 # TODO: No idea how such a feature looks like
# /-------------------------------------------------------

# --------------------------------------------------------
snm_dummy_graph_features_2 = []

# ring
snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(2, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["r"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["r"])
snm_dummy_graph_features_2[-1].add_edge(3, 2, label="g")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(4, 5, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 5, label="g")
snm_dummy_graph_features_2[-1].add_edge(6, 7, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["r"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_edge(2, 1, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 2, label="g")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(4, 5, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 5, label="g")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["r"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(9, labels=["b"])
snm_dummy_graph_features_2[-1].add_edge(2, 1, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 2, label="g")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(4, 5, label="n")
snm_dummy_graph_features_2[-1].add_edge(9, 1, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["r"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(9, labels=["b"])
snm_dummy_graph_features_2[-1].add_edge(2, 1, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 2, label="g")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(9, 8, label="g")
snm_dummy_graph_features_2[-1].add_edge(9, 1, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["r"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(9, labels=["b"])
snm_dummy_graph_features_2[-1].add_edge(2, 1, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 2, label="g")
snm_dummy_graph_features_2[-1].add_edge(7, 8, label="n")
snm_dummy_graph_features_2[-1].add_edge(9, 8, label="g")
snm_dummy_graph_features_2[-1].add_edge(9, 1, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["r"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(9, labels=["b"])
snm_dummy_graph_features_2[-1].add_edge(2, 1, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(7, 8, label="n")
snm_dummy_graph_features_2[-1].add_edge(9, 8, label="g")
snm_dummy_graph_features_2[-1].add_edge(9, 1, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["r"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(9, labels=["b"])
snm_dummy_graph_features_2[-1].add_edge(6, 5, label="g")
snm_dummy_graph_features_2[-1].add_edge(6, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(7, 8, label="n")
snm_dummy_graph_features_2[-1].add_edge(9, 8, label="g")
snm_dummy_graph_features_2[-1].add_edge(9, 1, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(4, labels=["r"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["r"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(9, labels=["b"])
snm_dummy_graph_features_2[-1].add_edge(4, 5, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 5, label="g")
snm_dummy_graph_features_2[-1].add_edge(6, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(7, 8, label="n")
snm_dummy_graph_features_2[-1].add_edge(9, 8, label="g")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(3, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["r"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["b"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["r"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["b"])
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(4, 5, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 5, label="g")
snm_dummy_graph_features_2[-1].add_edge(6, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(7, 8, label="n")

# chain
snm_dummy_graph_features_2 += snm_dummy_graph_features_2[6:] + snm_dummy_graph_features_2[:2]

# other
snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["b", "r"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["G"])
snm_dummy_graph_features_2[-1].add_edge(1, 2, label="n")

# buddy
buddy_feature = nx.MultiDiGraph()
buddy_feature.add_node(1, labels=["0"])
buddy_feature.add_node(2, labels=["0"])
buddy_feature.add_node(3, labels=["0"])
buddy_feature.add_node(4, labels=["0"])
buddy_feature.add_node(5, labels=["0"])
buddy_feature.add_node(6, labels=["0"])
buddy_feature.add_edge(1, 4, label="n")
buddy_feature.add_edge(1, 5, label="n")
buddy_feature.add_edge(1, 6, label="n")
buddy_feature.add_edge(2, 4, label="n")
buddy_feature.add_edge(2, 5, label="n")
buddy_feature.add_edge(2, 6, label="n")
buddy_feature.add_edge(3, 4, label="n")
buddy_feature.add_edge(3, 5, label="n")
buddy_feature.add_edge(3, 6, label="n")
for i in range(20):
    snm_dummy_graph_features_2.append(buddy_feature)

# other
snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["0"])

# cube
snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(0, labels=["G"]) # hub
snm_dummy_graph_features_2[-1].add_node(1, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["G"])
snm_dummy_graph_features_2[-1].add_edge(0, 1, label="n")
snm_dummy_graph_features_2[-1].add_edge(0, 2, label="n")
snm_dummy_graph_features_2[-1].add_edge(0, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(1, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(1, 6, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 5, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 5, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 6, label="n")

#other
snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["G"])

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["G"])
snm_dummy_graph_features_2[-1].add_edge(1, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")

# wheel
for feature in snm_dummy_graph_features_2[4:0:-1] + snm_dummy_graph_features_2[0:1] + snm_dummy_graph_features_2[8:4:-1]:
    snm_dummy_graph_features_2.append(feature.copy())
    snm_dummy_graph_features_2[-1].add_node(10, labels=["G"])
    for node in snm_dummy_graph_features_2[-1].nodes_iter():
        if node != 10:
            snm_dummy_graph_features_2[-1].add_edge(10, node, label="n")

# rule 5.2.2.0
snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 9,10
snm_dummy_graph_features_2[-1].add_node(0, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(9, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(10, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(11, labels=["G"])
snm_dummy_graph_features_2[-1].add_edge(0, 10, label="n")
snm_dummy_graph_features_2[-1].add_edge(0, 11, label="n")
snm_dummy_graph_features_2[-1].add_edge(8, 9, label="n")
snm_dummy_graph_features_2[-1].add_edge(9, 10, label="n")
snm_dummy_graph_features_2[-1].add_edge(9, 11, label="n")
snm_dummy_graph_features_2[-1].add_edge(10, 11, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 0,10
snm_dummy_graph_features_2[-1].add_node(0, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(1, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(9, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(10, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(11, labels=["G"])
snm_dummy_graph_features_2[-1].add_edge(0, 1, label="n")
snm_dummy_graph_features_2[-1].add_edge(0, 10, label="n")
snm_dummy_graph_features_2[-1].add_edge(0, 11, label="n")
snm_dummy_graph_features_2[-1].add_edge(9, 10, label="n")
snm_dummy_graph_features_2[-1].add_edge(9, 11, label="n")
snm_dummy_graph_features_2[-1].add_edge(10, 11, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 8,9
snm_dummy_graph_features_2[-1].add_node(6, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(9, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(10, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(11, labels=["G"])
snm_dummy_graph_features_2[-1].add_edge(6, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 8, label="n")
snm_dummy_graph_features_2[-1].add_edge(7, 8, label="n")
snm_dummy_graph_features_2[-1].add_edge(8, 9, label="n")
snm_dummy_graph_features_2[-1].add_edge(9, 10, label="n")
snm_dummy_graph_features_2[-1].add_edge(9, 11, label="n")
snm_dummy_graph_features_2[-1].add_edge(10, 11, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 9,11
snm_dummy_graph_features_2[-1].add_node(0, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(9, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(10, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(11, labels=["G"])
snm_dummy_graph_features_2[-1].add_edge(0, 10, label="n")
snm_dummy_graph_features_2[-1].add_edge(0, 11, label="n")
snm_dummy_graph_features_2[-1].add_edge(8, 9, label="n")
snm_dummy_graph_features_2[-1].add_edge(9, 10, label="n")
snm_dummy_graph_features_2[-1].add_edge(9, 11, label="n")
snm_dummy_graph_features_2[-1].add_edge(10, 11, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 6,7
snm_dummy_graph_features_2[-1].add_node(5, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(5, 6, label="n")
snm_dummy_graph_features_2[-1].add_edge(5, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 8, label="n")
snm_dummy_graph_features_2[-1].add_edge(7, 8, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 6,8
snm_dummy_graph_features_2[-1].add_node(5, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(9, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(5, 6, label="n")
snm_dummy_graph_features_2[-1].add_edge(5, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 8, label="n")
snm_dummy_graph_features_2[-1].add_edge(7, 8, label="n")
snm_dummy_graph_features_2[-1].add_edge(8, 9, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 10,11
snm_dummy_graph_features_2[-1].add_node(0, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(9, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(10, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(11, labels=["G"])
snm_dummy_graph_features_2[-1].add_edge(0, 10, label="n")
snm_dummy_graph_features_2[-1].add_edge(0, 11, label="n")
snm_dummy_graph_features_2[-1].add_edge(9, 10, label="n")
snm_dummy_graph_features_2[-1].add_edge(9, 11, label="n")
snm_dummy_graph_features_2[-1].add_edge(10, 11, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 2,4
snm_dummy_graph_features_2[-1].add_node(1, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(1, 2, label="n")
snm_dummy_graph_features_2[-1].add_edge(1, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(4, 5, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 0,1
snm_dummy_graph_features_2[-1].add_node(0, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(1, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(10, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(11, labels=["G"])
snm_dummy_graph_features_2[-1].add_edge(0, 10, label="n")
snm_dummy_graph_features_2[-1].add_edge(0, 11, label="n")
snm_dummy_graph_features_2[-1].add_edge(0, 1, label="n")
snm_dummy_graph_features_2[-1].add_edge(1, 2, label="n")
snm_dummy_graph_features_2[-1].add_edge(1, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(10, 11, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 1,2
snm_dummy_graph_features_2[-1].add_node(0, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(1, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(0, 1, label="n")
snm_dummy_graph_features_2[-1].add_edge(1, 2, label="n")
snm_dummy_graph_features_2[-1].add_edge(1, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 5,6
snm_dummy_graph_features_2[-1].add_node(4, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(4, 5, label="n")
snm_dummy_graph_features_2[-1].add_edge(5, 6, label="n")
snm_dummy_graph_features_2[-1].add_edge(5, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 8, label="n")
snm_dummy_graph_features_2[-1].add_edge(7, 8, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 5,7
snm_dummy_graph_features_2[-1].add_node(4, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(4, 5, label="n")
snm_dummy_graph_features_2[-1].add_edge(5, 6, label="n")
snm_dummy_graph_features_2[-1].add_edge(5, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 8, label="n")
snm_dummy_graph_features_2[-1].add_edge(7, 8, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 3,4
snm_dummy_graph_features_2[-1].add_node(1, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(1, 2, label="n")
snm_dummy_graph_features_2[-1].add_edge(1, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(4, 5, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 7,8
snm_dummy_graph_features_2[-1].add_node(5, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(9, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(5, 6, label="n")
snm_dummy_graph_features_2[-1].add_edge(5, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 8, label="n")
snm_dummy_graph_features_2[-1].add_edge(7, 8, label="n")
snm_dummy_graph_features_2[-1].add_edge(8, 9, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 1,3
snm_dummy_graph_features_2[-1].add_node(0, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(1, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(0, 1, label="n")
snm_dummy_graph_features_2[-1].add_edge(1, 2, label="n")
snm_dummy_graph_features_2[-1].add_edge(1, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 4,5
snm_dummy_graph_features_2[-1].add_node(2, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(2, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(4, 5, label="n")
snm_dummy_graph_features_2[-1].add_edge(5, 6, label="n")
snm_dummy_graph_features_2[-1].add_edge(5, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 7, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 2,3
snm_dummy_graph_features_2[-1].add_node(1, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(1, 2, label="n")
snm_dummy_graph_features_2[-1].add_edge(1, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 0,11
snm_dummy_graph_features_2[-1].add_node(0, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(1, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(9, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(10, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(11, labels=["G"])
snm_dummy_graph_features_2[-1].add_edge(0, 1, label="n")
snm_dummy_graph_features_2[-1].add_edge(0, 10, label="n")
snm_dummy_graph_features_2[-1].add_edge(0, 11, label="n")
snm_dummy_graph_features_2[-1].add_edge(9, 10, label="n")
snm_dummy_graph_features_2[-1].add_edge(9, 11, label="n")
snm_dummy_graph_features_2[-1].add_edge(10, 11, label="n")

# other
snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["G"])
snm_dummy_graph_features_2[-1].add_edge(1, 2, label="n")
snm_dummy_graph_features_2[-1].add_edge(1, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 3, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["G"])
snm_dummy_graph_features_2[-1].add_edge(1, 2, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 5, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["G"])
snm_dummy_graph_features_2[-1].add_edge(1, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(4, 5, label="n")

# rule 5.2.4.0
snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 1,2
snm_dummy_graph_features_2[-1].add_node(1, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(1, 2, label="n")
snm_dummy_graph_features_2[-1].add_edge(1, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 6,8
snm_dummy_graph_features_2[-1].add_node(5, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(5, 6, label="n")
snm_dummy_graph_features_2[-1].add_edge(5, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 8, label="n")
snm_dummy_graph_features_2[-1].add_edge(7, 8, label="n")

snm_dummy_graph_features_2.append(snm_dummy_graph_features_2[-1]) # 7,8

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 1,3
snm_dummy_graph_features_2[-1].add_node(1, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(1, 2, label="n")
snm_dummy_graph_features_2[-1].add_edge(1, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 2,4
snm_dummy_graph_features_2[-1].add_node(1, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(1, 2, label="n")
snm_dummy_graph_features_2[-1].add_edge(1, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(4, 5, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 6,7
snm_dummy_graph_features_2[-1].add_node(5, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(5, 6, label="n")
snm_dummy_graph_features_2[-1].add_edge(5, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 8, label="n")
snm_dummy_graph_features_2[-1].add_edge(7, 8, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 5,6
snm_dummy_graph_features_2[-1].add_node(4, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(4, 5, label="n")
snm_dummy_graph_features_2[-1].add_edge(5, 6, label="n")
snm_dummy_graph_features_2[-1].add_edge(5, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 8, label="n")
snm_dummy_graph_features_2[-1].add_edge(7, 8, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 5,7
snm_dummy_graph_features_2[-1].add_node(4, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(8, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(4, 5, label="n")
snm_dummy_graph_features_2[-1].add_edge(5, 6, label="n")
snm_dummy_graph_features_2[-1].add_edge(5, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 8, label="n")
snm_dummy_graph_features_2[-1].add_edge(7, 8, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 3,4
snm_dummy_graph_features_2[-1].add_node(1, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(1, 2, label="n")
snm_dummy_graph_features_2[-1].add_edge(1, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(4, 5, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 4,5
snm_dummy_graph_features_2[-1].add_node(2, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(5, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(6, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(7, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(2, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(4, 5, label="n")
snm_dummy_graph_features_2[-1].add_edge(5, 6, label="n")
snm_dummy_graph_features_2[-1].add_edge(5, 7, label="n")
snm_dummy_graph_features_2[-1].add_edge(6, 7, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph()) # 2,3
snm_dummy_graph_features_2[-1].add_node(1, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(1, 2, label="n")
snm_dummy_graph_features_2[-1].add_edge(1, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 3, label="n")
snm_dummy_graph_features_2[-1].add_edge(2, 4, label="n")
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")

# other
snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(3, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(4, labels=["0"])
snm_dummy_graph_features_2[-1].add_edge(3, 4, label="n")

snm_dummy_graph_features_2.append(nx.MultiDiGraph())
snm_dummy_graph_features_2[-1].add_node(1, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(2, labels=["0"])
snm_dummy_graph_features_2[-1].add_node(10, labels=["G"])
snm_dummy_graph_features_2[-1].add_node(11, labels=["G"])
snm_dummy_graph_features_2[-1].add_edge(10, 11, label="n")
# /-------------------------------------------------------
